import type { Movie, TVShow } from '@/types';

/** Curated catalog used when TMDB API key is missing or invalid */
export const FALLBACK_MOVIES: Movie[] = [
  { id: 278, title: 'The Shawshank Redemption', overview: 'Two imprisoned men bond over years, finding redemption through acts of common decency.', poster_path: '/9cqNdd0tGF87JON9kpHAfspsCK7.jpg', backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg', release_date: '1994-09-23', vote_average: 8.7, genre_ids: [18, 80] },
  { id: 238, title: 'The Godfather', overview: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', backdrop_path: '/tmP7SxRZVqGkecbYhQ0eocAUwLR.jpg', release_date: '1972-03-14', vote_average: 8.7, genre_ids: [18, 80] },
  { id: 240, title: 'The Godfather Part II', overview: 'The early life and career of Vito Corleone in 1920s New York City is portrayed.', poster_path: '/hek3onQjkcBb9FXAAchfktgvGWC.jpg', backdrop_path: '/kGzBuGjTyMzav1Apex1AQtNqven.jpg', release_date: '1974-12-20', vote_average: 8.6, genre_ids: [18, 80] },
  { id: 424, title: 'Schindler\'s List', overview: 'Industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', poster_path: '/sF1U4EUQS8YHUYjNl3pMGWR0Wec.jpg', backdrop_path: '/loRmKPaLUdoK2z6wXkP5DEJppog.jpg', release_date: '1993-12-15', vote_average: 8.6, genre_ids: [18, 36, 10752] },
  { id: 155, title: 'The Dark Knight', overview: 'Batman must accept one of the greatest psychological tests to fight injustice.', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_path: '/hkBaDkMWbLaf8B1lsWsNW7ls5vF.jpg', release_date: '2008-07-18', vote_average: 8.5, genre_ids: [28, 80, 18] },
  { id: 497, title: 'The Green Mile', overview: 'A death row guard learns a supernatural secret from an inmate with a mysterious gift.', poster_path: '/velWPhVMQeQKcxggNEu8gXsDqXQ.jpg', backdrop_path: '/l6h06InZVL5pMxG9Okx6EOn5jXU.jpg', release_date: '1999-12-10', vote_average: 8.5, genre_ids: [14, 18, 80] },
  { id: 122, title: 'The Lord of the Rings: The Return of the King', overview: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army.', poster_path: '/rCzpDGLbOoPwLjyOmNWcC5H3XLI.jpg', backdrop_path: '/2u7kba9a0Tt4ZB6Xv0fQZ9j2Y5k.jpg', release_date: '2003-12-17', vote_average: 8.5, genre_ids: [12, 14, 28] },
  { id: 680, title: 'Pulp Fiction', overview: 'The lives of two mob hitmen, a boxer, and others intertwine in four tales of violence.', poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', backdrop_path: '/suaEOtz1R5QvSEQAN9qAUwpGnPy.jpg', release_date: '1994-10-14', vote_average: 8.5, genre_ids: [53, 80] },
  { id: 13, title: 'Forrest Gump', overview: 'The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man.', poster_path: '/arw2vcBveWOVZtf6prN4gC6cieT.jpg', backdrop_path: '/7c9UVPPiQPlqax9LXUFU7WJuSfy.jpg', release_date: '1994-07-06', vote_average: 8.5, genre_ids: [35, 18, 10749] },
  { id: 27205, title: 'Inception', overview: 'A thief who steals corporate secrets through dream-sharing technology is offered a chance at redemption.', poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6d.jpg', backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoFX.jpg', release_date: '2010-07-16', vote_average: 8.4, genre_ids: [28, 878, 12] },
  { id: 157336, title: 'Interstellar', overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', backdrop_path: '/rAiYTyKGcUOVBHp4JLDdssLUvO.jpg', release_date: '2014-11-07', vote_average: 8.4, genre_ids: [12, 18, 878] },
  { id: 550, title: 'Fight Club', overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', backdrop_path: '/52AvEM0aJq2M14Xz7Qkf8aYh0NH.jpg', release_date: '1999-10-15', vote_average: 8.4, genre_ids: [18] },
  { id: 299536, title: 'Avengers: Infinity War', overview: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat Thanos.', poster_path: '/7WsyChQLEftFiDOVTGkv3h1hyBl.jpg', backdrop_path: '/lmZFxXlEUWKGjYZiC4BXIYyH0uw.jpg', release_date: '2018-04-27', vote_average: 8.3, genre_ids: [12, 28, 878] },
  { id: 299534, title: 'Avengers: Endgame', overview: 'After the devastating events of Infinity War, the universe is in ruins.', poster_path: '/or06FN3Dka5tukK07F9TWejYv9x.jpg', backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', release_date: '2019-04-26', vote_average: 8.3, genre_ids: [12, 28, 878] },
  { id: 872585, title: 'Oppenheimer', overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg', release_date: '2023-07-21', vote_average: 8.1, genre_ids: [18, 36] },
  { id: 346698, title: 'Barbie', overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.', poster_path: '/iuFNQS7RVPaWye94vVKNuMce6R4.jpg', backdrop_path: '/ctMTH7VgFeeaH7YAOqHYYkMadRC.jpg', release_date: '2023-07-21', vote_average: 7.0, genre_ids: [35, 12] },
  { id: 823464, title: 'Godzilla x Kong: The New Empire', overview: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as a hidden threat emerges.', poster_path: '/z1p34xy7YP15N06g01hAmn0vR1U.jpg', backdrop_path: '/xOMo8REKCEZnV7y1TQN6B5nUmTp.jpg', release_date: '2024-03-29', vote_average: 7.2, genre_ids: [28, 878, 12] },
  { id: 786892, title: 'Furiosa: A Mad Max Saga', overview: 'The origin story of renegade warrior Furiosa before her encounter with Mad Max.', poster_path: '/iM64FgDHB7PtAfVK-subglFAAvO.jpg', backdrop_path: '/yDHYDeKq5f1gEImA8cpM2-4en7v.jpg', release_date: '2024-05-24', vote_average: 7.6, genre_ids: [28, 878, 12] },
  { id: 693134, title: 'Dune: Part Two', overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators.', poster_path: '/1pdfLvkbY9ohJl64jS1CL25Qhbzu.jpg', backdrop_path: '/xOMo8REKCEZnV7y1TQN6B5nUmTp.jpg', release_date: '2024-03-01', vote_average: 8.2, genre_ids: [878, 12] },
  { id: 414906, title: 'The Batman', overview: 'Batman ventures into Gotham City\'s underworld when a sadistic killer leaves behind a trail of cryptic clues.', poster_path: '/b0Pl0SM4a9PCL93arGRAuo2hT3B.jpg', backdrop_path: '/xHrp2Bf7jWpWIDEoVRmViSer4oU.jpg', release_date: '2022-03-04', vote_average: 7.7, genre_ids: [80, 9648, 53] },
];

export const FALLBACK_TV: TVShow[] = [
  { id: 1396, name: 'Breaking Bad', overview: 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.', poster_path: '/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', backdrop_path: '/tsRy63Mu9cl8tBg2Bp8v8BnJlZ.jpg', first_air_date: '2008-01-20', vote_average: 8.9, genre_ids: [18, 80] },
  { id: 1399, name: 'Game of Thrones', overview: 'Nine noble families fight for control over the lands of Westeros.', poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJ2.jpg', backdrop_path: '/2OMB0ynKlyIenMJWI2BwYeJ7QrO.jpg', first_air_date: '2011-04-17', vote_average: 8.4, genre_ids: [10765, 18, 10759] },
  { id: 66732, name: 'Stranger Things', overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments.', poster_path: '/49WJfeN0moxb9IPfe0yTiOGDOC5.jpg', backdrop_path: '/56v2KjBlU4XaOv9rAGR85zfVjV3.jpg', first_air_date: '2016-07-15', vote_average: 8.6, genre_ids: [18, 10765, 9648] },
  { id: 82856, name: 'The Mandalorian', overview: 'The travels of a lone bounty hunter in the outer reaches of the galaxy.', poster_path: '/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg', backdrop_path: '/9ijMGlJKqcslsw86S7aT4Wh4S2p.jpg', first_air_date: '2019-11-12', vote_average: 8.5, genre_ids: [10765, 10759, 18] },
  { id: 94997, name: 'House of the Dragon', overview: 'The Targaryen dynasty is at the absolute apex of its power.', poster_path: '/z2y9822vWk3N1x0Mf4N8U0K4qJd.jpg', backdrop_path: '/1M876KPjulVwppKPpssdx03OM3a.jpg', first_air_date: '2022-08-21', vote_average: 8.4, genre_ids: [10765, 18, 10759] },
  { id: 76479, name: 'The Boys', overview: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', poster_path: '/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg', backdrop_path: '/2zmTngn1tGF1EFFasmTUHTcJvsO.jpg', first_air_date: '2019-07-26', vote_average: 8.5, genre_ids: [10765, 10759] },
  { id: 100088, name: 'The Last of Us', overview: 'Twenty years after modern civilization has been destroyed, Joel and Ellie traverse a post-apocalyptic America.', poster_path: '/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg', backdrop_path: '/suopoADq0k1bzdq3Kc6MA82ATT3.jpg', first_air_date: '2023-01-15', vote_average: 8.6, genre_ids: [18, 10765] },
  { id: 95557, name: 'Invincible', overview: 'An adult animated series based on the Skybound/Image comic about a teenager whose father is the most powerful superhero.', poster_path: '/yDWJYRAwMNKbIYT8Z25qE6fYHGr.jpg', backdrop_path: '/1M876KPjulVwppKPpssdx03OM3a.jpg', first_air_date: '2021-03-26', vote_average: 8.7, genre_ids: [16, 10765, 10759] },
  { id: 1402, name: 'The Walking Dead', overview: 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors.', poster_path: '/rqeYMLryjcawh2ihgjip3KycmAH.jpg', backdrop_path: '/xTD5Ypja3QWyJMYmsdwQ2fAVtbx.jpg', first_air_date: '2010-10-31', vote_average: 8.1, genre_ids: [10765, 18, 10759] },
  { id: 456, name: 'The Simpsons', overview: 'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family.', poster_path: '/q0F4cKKnryFbMXiQ9WYXn2Ss4RG.jpg', backdrop_path: '/8c7iZJqcdZ9D7M9c9k0Ss1SSp3S.jpg', first_air_date: '1989-12-17', vote_average: 8.0, genre_ids: [16, 35] },
  { id: 1418, name: 'The Big Bang Theory', overview: 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists.', poster_path: '/ooBGRQBdbGzBxAVfExiO8r7knoA.jpg', backdrop_path: '/8c7iZJqcdZ9D7M9c9k0Ss1SSp3S.jpg', first_air_date: '2007-09-24', vote_average: 7.9, genre_ids: [35] },
  { id: 60735, name: 'The Flash', overview: 'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning.', poster_path: '/lJA2RCMfsWoskqlQhXPSddQDD3f.jpg', backdrop_path: '/8c7iZJqcdZ9D7M9c9k0Ss1SSp3S.jpg', first_air_date: '2014-10-07', vote_average: 7.8, genre_ids: [18, 10765] },
  { id: 71912, name: 'The Witcher', overview: 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world.', poster_path: '/7vjaCdMw15FEbXy0UfydQHB6IZO.jpg', backdrop_path: '/jBJweaczWFX7DazNlp0XhNc5vu1.jpg', first_air_date: '2019-12-20', vote_average: 8.0, genre_ids: [18, 10759, 10765] },
  { id: 114410, name: 'Shōgun', overview: 'In Japan in the year 1600, a mysterious European ship is found marooned in a nearby fishing village.', poster_path: '/7O4iVfOMQmdCS3Ogwp03upV0v0p.jpg', backdrop_path: '/1M876KPjulVwppKPpssdx03OM3a.jpg', first_air_date: '2024-02-27', vote_average: 8.5, genre_ids: [18, 10759] },
  { id: 106379, name: 'Fallout', overview: 'The story of haves and have-nots in a world in which there\'s almost nothing left to have.', poster_path: '/AweUV5ZB1R7uNjJ0t1al3Z8Zw96.jpg', backdrop_path: '/1M876KPjulVwppKPpssdx03OM3a.jpg', first_air_date: '2024-04-10', vote_average: 8.3, genre_ids: [10765, 18] },
];

export function isTmdbKeyConfigured(): boolean {
  const key = import.meta.env.VITE_TMDB_API_KEY;
  return Boolean(key && key !== 'your_tmdb_api_key_here');
}
